---
title: "Adjustment Analysis for the VQI FBVAR Dataset"
author: "Jennifer Ci, Thu Vu, Lily Hanyi Wang"
output: pdf_document
---

```{r library, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
knitr::opts_chunk$set(fig.width=20, fig.height=20)

library(tidyverse)
library(table1)
library(survival)
library(Hmisc)
library(ggplot2)
library(ggpubr)
library(corrplot)
library(caret)
library(survminer)

```

```{r setup wd}
## ------------- working directories for Lily ----------
# wd_lily = '/Users/hanyiwang/Desktop/Comparative-analysis-of-treatments-of-CAA'
# path_lily = c("../data/FBVAR.csv")


## ------------- working directories for Jenn ----------
# wd_jenn = 
# path_jenn = 

## ------------- working directories for Thu ----------
wd_thu = '/Users/thuvu/Desktop/Comparative-analysis-of-treatments-of-CAA'
path_thu = c("FBVAR.csv")

## ------------- read data ----------
# setwd(wd_lily)
# FBVAR = read.csv(path_lily)

# setwd(wd_jenn)
# FBVAR = read.csv(path_jenn)

setwd(wd_thu)
FBVAR = read.csv(path_thu)

```

## Correlation matrix

```{r}
## Correlation matrix
matrix <- FBVAR %>%
    select_if(is.numeric) %>% subset(., select = -1)%>%
    cor(.,use = "complete")

corrplot(matrix, method="number")

```

## Survival analysis

Unadjusted survival curves. Time scale changed from calendar days to calendar years. Used log rank test to produce p-value. Median survival never reached. 

Any changes needed? (e.g, time scale, colors, change to at risk table, add number of censored and/or uncensored events, etc.)

```{r, fig.width=8, fig.height=6}
## Survival analysis
# event = 1 for uncensored (Dead), event = 0 for censored (Alive)
FBVAR$event <- ifelse(FBVAR$DEAD=="TRUE", 1, 0)

tte <- FBVAR %>% with(Surv(PROC_SURVIVALDAYS/365, event))

# compute survival curves
fit <- survfit(tte ~ PRESENTATION, data=FBVAR)

# plotting Kaplan-Meier Curves
ggsurvplot(fit,
           pval = TRUE, 
           risk.table = TRUE, 
           linetype = "strata",
           surv.median.line = "hv", 
           ggtheme = theme_bw(), 
           xlab = "Time in years",
           legend.labs = c("Asymptomatic", "Symptomatic"),
           break.time.by=1) 
```

\newpage

## Code Appendix

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE,include=TRUE}
```
